package com.nickuc.login.security.hashing;

import com.nickuc.login.auth.message.FastMessageHandler;
import com.nickuc.login.auth.message.MessageProcessor;
import com.nickuc.login.auth.login.ParentLoginCheckpoint;
import com.nickuc.login.auth.login.SafeLoginBarrier;
import com.nickuc.login.config.PasswordHashContainer;
import com.nickuc.login.config.PasswordHashLoader;
import java.io.BufferedInputStream;
import java.io.BufferedOutputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.util.Collections;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.Map.Entry;
import java.util.function.Consumer;
import javax.annotation.Nullable;

public class PrimaryPasswordHashVerifier {
   private final Map<String, byte[]> sessions = new HashMap<>();
   private final String name;
   private final File dataFile;

   @Nullable
   public synchronized Byte resolveByte(String target) {
      return this.resolveByte(target, null);
   }

   public synchronized PrimaryPasswordHashVerifier handlePrimaryPasswordHashVerifier(String target, Consumer<ParentLoginCheckpoint> input) {
      return this.computePrimaryPasswordHashVerifier(target, FastMessageHandler.buildPayload(input));
   }

   public synchronized boolean hasState(String target) {
      return this.sessions.containsKey(target);
   }

   public synchronized PrimaryPasswordHashVerifier resolvePrimaryPasswordHashVerifier(String target, String input) {
      if (input == null) {
         throw new IllegalArgumentException("Value cannot be null!");
      } else {
         return this.computePrimaryPasswordHashVerifier(target, input.getBytes(StandardCharsets.UTF_8));
      }
   }

   public synchronized void handleTask() {
      try {
         this.sessions.clear();
         if (this.dataFile.exists()) {
            BufferedInputStream target = MessageProcessor.createBufferedInputStream(this.dataFile);

            try {
               DataInputStream input = new DataInputStream(target);

               try {
                  int output = input.readInt();
                  if (output > 0) {
                     throw new UnsupportedOperationException(
                        "Unable to read " + this.dataFile + ": the file was generated by a newer version. " + output + " > " + 0
                     );
                  }

                  int context = input.readInt();

                  for (int data = 0; data < context; data++) {
                     String value = input.readUTF();
                     int result = input.readInt();
                     byte[] request = new byte[result];
                     input.readFully(request);
                     this.sessions.put(value, request);
                  }
               } finally {
                  if (Collections.singletonList(input).get(0) != null) {
                     input.close();
                  }
               }
            } finally {
               if (Collections.singletonList(target).get(0) != null) {
                  target.close();
               }
            }
         } else {
            File option = new File(this.dataFile.getParentFile(), this.name.toLowerCase(Locale.ENGLISH) + ".db");
            if (option.exists()) {
               PasswordHashLoader setting = new PasswordHashLoader(option);

               for (String attribute : setting.loadSet("")) {
                  if (attribute != null && !attribute.isEmpty()) {
                     String parameter = setting.b(attribute);
                     if (parameter != null) {
                        if (!parameter.isEmpty()) {
                           parameter = SafeLoginBarrier.computeMessage(parameter);
                        }

                        this.sessions.put(attribute.replace(':', '.'), parameter.getBytes(StandardCharsets.UTF_8));
                     }
                  }
               }

               this.sendTask();
               if (!option.delete()) {
                  option.deleteOnExit();
               }
            }
         }
      } catch (IOException subject) {
         PasswordHashContainer.processMessage("Unable to load " + this.dataFile + " file", subject);
      }
   }

   public synchronized void sendTask() {
      try {
         MessageProcessor.isState(this.dataFile);
         BufferedOutputStream target = MessageProcessor.computeBufferedOutputStream(this.dataFile);

         try {
            DataOutputStream input = new DataOutputStream(target);

            try {
               input.writeInt(0);
               input.writeInt(this.sessions.size());

               for (Entry context : this.sessions.entrySet()) {
                  input.writeUTF((String)context.getKey());
                  byte[] data = (byte[])context.getValue();
                  input.writeInt(data.length);
                  input.write(data);
               }

               input.flush();
            } finally {
               if (Collections.singletonList(input).get(0) != null) {
                  input.close();
               }
            }
         } finally {
            if (Collections.singletonList(target).get(0) != null) {
               target.close();
            }
         }
      } catch (IOException payload) {
         throw new RuntimeException("Unable to save " + this.dataFile + " file", payload);
      }
   }

   public PrimaryPasswordHashVerifier(String target, File input) {
      this.name = target;
      this.dataFile = input;
      this.handleTask();
   }

   public synchronized boolean isState(String target) {
      return this.hasState(target, false);
   }

   public synchronized Byte resolveByte(String target, @Nullable Byte input) {
      byte[] output = this.createPayload(target);
      return output != null && output.length > 0 ? output[0] : input;
   }

   public synchronized PrimaryPasswordHashVerifier handlePrimaryPasswordHashVerifier(String target, byte input) {
      return this.computePrimaryPasswordHashVerifier(target, new byte[]{input});
   }

   public synchronized boolean hasState(String target, boolean input) {
      Byte output = this.resolveByte(target);
      return output != null ? output == 1 : input;
   }

   public synchronized PrimaryPasswordHashVerifier createPrimaryPasswordHashVerifier(String target) {
      this.sessions.remove(target);
      return this;
   }

   @Nullable
   public synchronized byte[] createPayload(String target) {
      return this.sessions.get(target);
   }

   @Nullable
   public synchronized String loadMessage(String target) {
      return this.loadMessage(target, null);
   }

   public synchronized PrimaryPasswordHashVerifier computePrimaryPasswordHashVerifier(String target, byte[] input) {
      if (input == null) {
         throw new IllegalArgumentException("Value cannot be null!");
      }

      this.sessions.put(target, input);
      return this;
   }

   public synchronized PrimaryPasswordHashVerifier createPrimaryPasswordHashVerifier(String target, boolean input) {
      return this.handlePrimaryPasswordHashVerifier(target, (byte)(input ? 1 : 0));
   }

   @Nullable
   public synchronized String loadMessage(String target, String input) {
      byte[] output = this.createPayload(target);
      return output != null ? new String(output, StandardCharsets.UTF_8) : input;
   }
}
