package com.nickuc.login.limbo;

import com.nickuc.login.auth.message.MessageProcessor;
import com.nickuc.login.config.PasswordHashContainer;
import com.nickuc.login.listener.bukkit.VerifiedLoginGuard;
import java.io.BufferedInputStream;
import java.io.DataInputStream;
import java.io.DataOutputStream;
import java.io.File;
import java.util.Collections;
import java.util.Locale;

import org.bukkit.GameMode;
import org.bukkit.Location;

public class LimboTracker {
   private final SpawnSession spawnSession;

   public void saveLimboStore(LimboStore target) {
      File input = target.dataFile;
      if (!input.exists()) {
         MessageProcessor.isState(input);
         DataOutputStream output = new DataOutputStream(MessageProcessor.computeBufferedOutputStream(input));

         try {
            output.writeInt(3);
            output.writeInt(this.loadCount(target));
            output.writeBoolean(target.primaryEnabled);
            output.writeBoolean(target.activeEnabled);
            output.writeBoolean(target.mainEnabled);
            GameMode context = target.gameMode;
            if (context != null) {
               output.writeUTF(context.name().toUpperCase(Locale.ENGLISH));
            }

            output.writeInt(target.activeCount);
            output.writeInt(target.count);
            output.writeDouble(target.ratio);
            output.writeFloat(target.activeFactor);
            output.writeFloat(target.factor);
            Location data = target.location;
            if (data != null) {
               VerifiedLoginGuard.fetchSharedLoginGuard().executeLocation(data, output);
            }

            output.flush();
         } finally {
            if (Collections.singletonList(output).get(0) != null) {
               output.close();
            }
         }
      }
   }

   private int loadCount(LimboStore target) {
      byte input = 0;
      if (target.gameMode != null) {
         input |= 2;
      }

      if (target.location != null) {
         input |= 4;
      }

      return input;
   }

   public void processLimboStore(LimboStore target, boolean input) {
      File output = target.dataFile;
      if (!output.exists()) {
         throw new IllegalStateException("Player limbo file does not exists!");
      }

      BufferedInputStream context = MessageProcessor.createBufferedInputStream(output);

      try {
         DataInputStream data = new DataInputStream(context);

         try {
            int value = data.readInt();
            if (value > 3) {
               throw new UnsupportedOperationException("Unable to read " + output + ": the file was generated by a newer version. " + value + " > " + 3);
            }

            int result = data.readInt();
            if ((result & 1) != 0) {
               data.skipBytes(4);

               for (int request = 0; request < data.readInt(); request++) {
                  data.skipBytes(4);
                  data.skipBytes(data.readInt());
               }
            }

            target.primaryEnabled = data.readBoolean();
            if (value >= 2) {
               target.activeEnabled = data.readBoolean();
               target.mainEnabled = data.readBoolean();
            }

            if ((result & 2) != 0) {
               String setting = data.readUTF();

               try {
                  target.gameMode = GameMode.valueOf(setting);
               } catch (IllegalArgumentException reference) {
                  target.gameMode = GameMode.SURVIVAL;
                  PasswordHashContainer.updateMessage("Gamemode \"" + setting + "\" not found, failing back to " + target.gameMode);
               }
            }

            target.activeCount = data.readInt();
            target.count = data.readInt();
            target.ratio = data.readDouble();
            target.activeFactor = data.readFloat();
            target.factor = data.readFloat();
            target.enabled = input;
            if (!input && (result & 4) != 0) {
               target.location = VerifiedLoginGuard.fetchSharedLoginGuard().handleLocation(data);
            }
         } finally {
            if (Collections.singletonList(data).get(0) != null) {
               data.close();
            }
         }
      } finally {
         if (Collections.singletonList(context).get(0) != null) {
            context.close();
         }
      }
   }

   public LimboTracker(SpawnSession target) {
      this.spawnSession = target;
   }
}
