package com.nickuc.login.model;

public enum LenientMessageKind {
   LENIENT_MESSAGE_KIND,
   ACTIVE_LENIENTMESSAGEKIND,
   PENDING_LENIENTMESSAGEKIND,
   CURRENT_LENIENTMESSAGEKIND,
   PRIMARY_LENIENTMESSAGEKIND,
   MAIN_LENIENTMESSAGEKIND,
   LOCAL_LENIENTMESSAGEKIND,
   REMOTE_LENIENTMESSAGEKIND,
   CACHED_LENIENTMESSAGEKIND,
   STORED_LENIENTMESSAGEKIND,
   VERIFIED_LENIENTMESSAGEKIND,
   AUTHENTICATED_LENIENTMESSAGEKIND,
   SHARED_LENIENTMESSAGEKIND,
   PRIVATE_LENIENTMESSAGEKIND,
   INTERNAL_LENIENTMESSAGEKIND,
   UPSTREAM_LENIENTMESSAGEKIND,
   INCOMING_LENIENTMESSAGEKIND,
   OUTGOING_LENIENTMESSAGEKIND,
   SECONDARY_LENIENTMESSAGEKIND,
   DIRECT_LENIENTMESSAGEKIND,
   LINKED_LENIENTMESSAGEKIND,
   ROOT_LENIENTMESSAGEKIND,
   TOP_LENIENTMESSAGEKIND,
   FAST_LENIENTMESSAGEKIND,
   SAFE_LENIENTMESSAGEKIND,
   SECURE_LENIENTMESSAGEKIND,
   OPEN_LENIENTMESSAGEKIND,
   READY_LENIENTMESSAGEKIND,
   LIVE_LENIENTMESSAGEKIND,
   ACTIVE_PENDING_LENIENTMESSAGEKIND,
   ACTIVE_CURRENT_LENIENTMESSAGEKIND,
   ACTIVE_PRIMARY_LENIENTMESSAGEKIND,
   ACTIVE_MAIN_LENIENTMESSAGEKIND,
   ACTIVE_LOCAL_LENIENTMESSAGEKIND,
   ACTIVE_REMOTE_LENIENTMESSAGEKIND,
   ACTIVE_CACHED_LENIENTMESSAGEKIND,
   ACTIVE_STORED_LENIENTMESSAGEKIND,
   ACTIVE_VERIFIED_LENIENTMESSAGEKIND,
   ACTIVE_AUTHENTICATED_LENIENTMESSAGEKIND,
   ACTIVE_SHARED_LENIENTMESSAGEKIND,
   ACTIVE_PRIVATE_LENIENTMESSAGEKIND;

   public String findMessage() {
      return this.name();
   }
}
