package com.nickuc.login.model;

public enum LocalPremiumState {
   LOCAL_PREMIUM_STATE,
   ACTIVE_LOCALPREMIUMSTATE,
   PENDING_LOCALPREMIUMSTATE,
   CURRENT_LOCALPREMIUMSTATE,
   PRIMARY_LOCALPREMIUMSTATE;
}
