package com.nickuc.login.platform.proxy;

import com.nickuc.login.auth.login.LoginCheckpoint;
import com.nickuc.login.protocol.PacketListener;
import java.lang.reflect.InvocationTargetException;
import java.util.function.Consumer;
import javax.annotation.Nullable;
import org.bukkit.Sound;

public enum QuickProxyState {
   QUICK_PROXY_STATE("AMBIENCE_CAVE", "AMBIENT_CAVE"),
   ACTIVE_QUICKPROXYSTATE("AMBIENCE_RAIN", "WEATHER_RAIN"),
   PENDING_QUICKPROXYSTATE("AMBIENCE_THUNDER", "ENTITY_LIGHTNING_THUNDER"),
   CURRENT_QUICKPROXYSTATE("ANVIL_BREAK", "BLOCK_ANVIL_BREAK"),
   PRIMARY_QUICKPROXYSTATE("ANVIL_LAND", "BLOCK_ANVIL_LAND"),
   MAIN_QUICKPROXYSTATE("ANVIL_USE", "BLOCK_ANVIL_USE"),
   LOCAL_QUICKPROXYSTATE("ARROW_HIT", "ENTITY_ARROW_HIT"),
   REMOTE_QUICKPROXYSTATE("BURP", "ENTITY_PLAYER_BURP"),
   CACHED_QUICKPROXYSTATE("CHEST_CLOSE", "ENTITY_CHEST_CLOSE"),
   STORED_QUICKPROXYSTATE("CHEST_OPEN", "ENTITY_CHEST_OPEN"),
   VERIFIED_QUICKPROXYSTATE("CLICK", "UI_BUTTON_CLICK"),
   AUTHENTICATED_QUICKPROXYSTATE("DOOR_CLOSE", "BLOCK_WOODEN_DOOR_CLOSE"),
   SHARED_QUICKPROXYSTATE("DOOR_OPEN", "BLOCK_WOODEN_DOOR_OPEN"),
   PRIVATE_QUICKPROXYSTATE("DRINK", "ENTITY_GENERIC_DRINK"),
   INTERNAL_QUICKPROXYSTATE("EAT", "ENTITY_GENERIC_EAT"),
   UPSTREAM_QUICKPROXYSTATE("EXPLODE", "ENTITY_GENERIC_EXPLODE"),
   INCOMING_QUICKPROXYSTATE("FALL_BIG", "ENTITY_GENERIC_BIG_FALL"),
   OUTGOING_QUICKPROXYSTATE("FALL_SMALL", "ENTITY_GENERIC_SMALL_FALL"),
   SECONDARY_QUICKPROXYSTATE("FIRE", "BLOCK_FIRE_AMBIENT"),
   DIRECT_QUICKPROXYSTATE("FIRE_IGNITE", "ITEM_FLINTANDSTEEL_USE"),
   LINKED_QUICKPROXYSTATE("FIZZ", "BLOCK_FIRE_EXTINGUISH"),
   ROOT_QUICKPROXYSTATE("FUSE", "ENTITY_TNT_PRIMED"),
   TOP_QUICKPROXYSTATE("GLASS", "BLOCK_GLASS_BREAK"),
   FAST_QUICKPROXYSTATE("HURT_FLESH", "ENTITY_PLAYER_HURT"),
   SAFE_QUICKPROXYSTATE("ITEM_BREAK", "ENTITY_ITEM_BREAK"),
   SECURE_QUICKPROXYSTATE("ITEM_PICKUP", "ENTITY_ITEM_PICKUP"),
   OPEN_QUICKPROXYSTATE("LAVA", "BLOCK_LAVA_AMBIENT"),
   READY_QUICKPROXYSTATE("LAVA_POP", "BLOCK_LAVA_POP"),
   LIVE_QUICKPROXYSTATE("LEVEL_UP", "ENTITY_PLAYER_LEVELUP"),
   ACTIVE_PENDING_QUICKPROXYSTATE("MINECART_BASE", "ENTITY_MINECART_RIDING"),
   ACTIVE_CURRENT_QUICKPROXYSTATE("MINECART_INSIDE", "ENTITY_MINECART_RIDING"),
   ACTIVE_PRIMARY_QUICKPROXYSTATE("NOTE_BASS", "BLOCK_NOTE_BASS", "BLOCK_NOTE_BLOCK_BASS"),
   ACTIVE_MAIN_QUICKPROXYSTATE("NOTE_PIANO", "BLOCK_NOTE_HARP", "BLOCK_NOTE_BLOCK_HARP"),
   ACTIVE_LOCAL_QUICKPROXYSTATE("NOTE_BASS_DRUM", "BLOCK_NOTE_BASEDRUM", "BLOCK_NOTE_BLOCK_BASEDRUM"),
   ACTIVE_REMOTE_QUICKPROXYSTATE("NOTE_STICKS", "BLOCK_NOTE_HAT"),
   ACTIVE_CACHED_QUICKPROXYSTATE("NOTE_BASS_GUITAR", "BLOCK_NOTE_BASS", "BLOCK_NOTE_BLOCK_HAT"),
   ACTIVE_STORED_QUICKPROXYSTATE("NOTE_SNARE_DRUM", "BLOCK_NOTE_SNARE", "BLOCK_NOTE_BLOCK_SNARE"),
   ACTIVE_VERIFIED_QUICKPROXYSTATE("NOTE_PLING", "BLOCK_NOTE_PLING", "BLOCK_NOTE_BLOCK_PLING"),
   ACTIVE_AUTHENTICATED_QUICKPROXYSTATE("ORB_PICKUP", "ENTITY_EXPERIENCE_ORB_PICKUP"),
   ACTIVE_SHARED_QUICKPROXYSTATE("PISTON_EXTEND", "BLOCK_PISTON_EXTEND"),
   ACTIVE_PRIVATE_QUICKPROXYSTATE("PISTON_RETRACT", "BLOCK_PISTON_CONTRACT"),
   ACTIVE_INTERNAL_QUICKPROXYSTATE("PORTAL", "BLOCK_PORTAL_AMBIENT"),
   ACTIVE_UPSTREAM_QUICKPROXYSTATE("PORTAL_TRAVEL", "BLOCK_PORTAL_TRAVEL"),
   ACTIVE_INCOMING_QUICKPROXYSTATE("PORTAL_TRIGGER", "BLOCK_PORTAL_TRIGGER"),
   ACTIVE_OUTGOING_QUICKPROXYSTATE("SHOOT_ARROW", "ENTITY_ARROW_SHOOT"),
   ACTIVE_SECONDARY_QUICKPROXYSTATE("SPLASH", "ENTITY_GENERIC_SPLASH"),
   ACTIVE_DIRECT_QUICKPROXYSTATE("SPLASH2", "ENTITY_BOBBER_SPLASH"),
   ACTIVE_LINKED_QUICKPROXYSTATE("STEP_GRASS", "BLOCK_GRASS_STEP"),
   ACTIVE_ROOT_QUICKPROXYSTATE("STEP_GRAVEL", "BLOCK_GRAVEL_STEP"),
   ACTIVE_TOP_QUICKPROXYSTATE("STEP_LADDER", "BLOCK_LADDER_STEP"),
   ACTIVE_FAST_QUICKPROXYSTATE("STEP_SAND", "BLOCK_SAND_STEP"),
   ACTIVE_SAFE_QUICKPROXYSTATE("STEP_SNOW", "BLOCK_SNOW_STEP"),
   ACTIVE_SECURE_QUICKPROXYSTATE("STEP_STONE", "BLOCK_STONE_STEP"),
   ACTIVE_OPEN_QUICKPROXYSTATE("STEP_WOOD", "BLOCK_WOOD_STEP"),
   ACTIVE_READY_QUICKPROXYSTATE("STEP_WOOL", "BLOCK_CLOTH_STEP"),
   ACTIVE_LIVE_QUICKPROXYSTATE("SWIM", "ENTITY_GENERIC_SWIM"),
   PENDING_ACTIVE_QUICKPROXYSTATE("WATER", "BLOCK_WATER_AMBIENT"),
   PENDING_CURRENT_QUICKPROXYSTATE("WOOD_CLICK", "BLOCK_WOOD_BUTTON_CLICK_ON"),
   PENDING_PRIMARY_QUICKPROXYSTATE("BAT_DEATH", "ENTITY_BAT_DEATH"),
   PENDING_MAIN_QUICKPROXYSTATE("BAT_HURT", "ENTITY_BAT_HURT"),
   PENDING_LOCAL_QUICKPROXYSTATE("BAT_IDLE", "ENTITY_BAT_AMBIENT"),
   PENDING_REMOTE_QUICKPROXYSTATE("BAT_LOOP", "ENTITY_BAT_LOOP"),
   PENDING_CACHED_QUICKPROXYSTATE("BAT_TAKEOFF", "ENTITY_BAT_TAKEOFF"),
   PENDING_STORED_QUICKPROXYSTATE("BLAZE_BREATH", "ENTITY_BLAZE_AMBIENT"),
   PENDING_VERIFIED_QUICKPROXYSTATE("BLAZE_DEATH", "ENTITY_BLAZE_DEATH"),
   PENDING_AUTHENTICATED_QUICKPROXYSTATE("BLAZE_HIT", "ENTITY_BLAZE_HURT"),
   PENDING_SHARED_QUICKPROXYSTATE("CAT_HISS", "ENTITY_CAT_HISS"),
   PENDING_PRIVATE_QUICKPROXYSTATE("CAT_HIT", "ENTITY_CAT_HURT"),
   PENDING_INTERNAL_QUICKPROXYSTATE("CAT_MEOW", "ENTITY_CAT_AMBIENT"),
   PENDING_UPSTREAM_QUICKPROXYSTATE("CAT_PURR", "ENTITY_CAT_PURR"),
   PENDING_INCOMING_QUICKPROXYSTATE("CAT_PURREOW", "ENTITY_CAT_PURREOW"),
   PENDING_OUTGOING_QUICKPROXYSTATE("CHICKEN_IDLE", "ENTITY_CHICKEN_AMBIENT"),
   PENDING_SECONDARY_QUICKPROXYSTATE("CHICKEN_HURT", "ENTITY_CHICKEN_HURT"),
   PENDING_DIRECT_QUICKPROXYSTATE("CHICKEN_EGG_POP", "ENTITY_CHICKEN_EGG"),
   PENDING_LINKED_QUICKPROXYSTATE("CHICKEN_WALK", "ENTITY_CHICKEN_STEP"),
   PENDING_ROOT_QUICKPROXYSTATE("COW_IDLE", "ENTITY_COW_AMBIENT"),
   PENDING_TOP_QUICKPROXYSTATE("COW_HURT", "ENTITY_COW_HURT"),
   PENDING_FAST_QUICKPROXYSTATE("COW_WALK", "ENTITY_COW_STEP"),
   PENDING_SAFE_QUICKPROXYSTATE("CREEPER_HISS", "ENTITY_CREEPER_PRIMED"),
   PENDING_SECURE_QUICKPROXYSTATE("CREEPER_DEATH", "ENTITY_CREEPER_DEATH"),
   PENDING_OPEN_QUICKPROXYSTATE("ENDERDRAGON_DEATH", "ENTITY_ENDERDRAGON_DEATH"),
   PENDING_READY_QUICKPROXYSTATE("ENDERDRAGON_GROWL", "ENTITY_ENDERDRAGON_GROWL"),
   PENDING_LIVE_QUICKPROXYSTATE("ENDERDRAGON_HIT", "ENTITY_ENDERDRAGON_HURT"),
   CURRENT_ACTIVE_QUICKPROXYSTATE("ENDERDRAGON_WINGS", "ENTITY_ENDERDRAGON_FLAP"),
   CURRENT_PENDING_QUICKPROXYSTATE("ENDERMAN_DEATH", "ENTITY_ENDERMEN_DEATH"),
   CURRENT_PRIMARY_QUICKPROXYSTATE("ENDERMAN_HIT", "ENTITY_ENDERMEN_HURT"),
   CURRENT_MAIN_QUICKPROXYSTATE("ENDERMAN_IDLE", "ENTITY_ENDERMEN_AMBIENT"),
   CURRENT_LOCAL_QUICKPROXYSTATE("ENDERMAN_TELEPORT", "ENTITY_ENDERMEN_TELEPORT"),
   CURRENT_REMOTE_QUICKPROXYSTATE("ENDERMAN_SCREAM", "ENTITY_ENDERMEN_SCREAM"),
   CURRENT_CACHED_QUICKPROXYSTATE("ENDERMAN_STARE", "ENTITY_ENDERMEN_STARE"),
   CURRENT_STORED_QUICKPROXYSTATE("GHAST_SCREAM", "ENTITY_GHAST_SCREAM"),
   CURRENT_VERIFIED_QUICKPROXYSTATE("GHAST_SCREAM2", "ENTITY_GHAST_HURT"),
   CURRENT_AUTHENTICATED_QUICKPROXYSTATE("GHAST_CHARGE", "ENTITY_GHAST_WARN"),
   CURRENT_SHARED_QUICKPROXYSTATE("GHAST_DEATH", "ENTITY_GHAST_DEATH"),
   CURRENT_PRIVATE_QUICKPROXYSTATE("GHAST_FIREBALL", "ENTITY_GHAST_SHOOT"),
   CURRENT_INTERNAL_QUICKPROXYSTATE("GHAST_MOAN", "ENTITY_GHAST_AMBIENT"),
   CURRENT_UPSTREAM_QUICKPROXYSTATE("IRONGOLEM_DEATH", "ENTITY_IRONGOLEM_DEATH"),
   CURRENT_INCOMING_QUICKPROXYSTATE("IRONGOLEM_HIT", "ENTITY_IRONGOLEM_HURT"),
   CURRENT_OUTGOING_QUICKPROXYSTATE("IRONGOLEM_THROW", "ENTITY_IRONGOLEM_ATTACK"),
   CURRENT_SECONDARY_QUICKPROXYSTATE("IRONGOLEM_WALK", "ENTITY_IRONGOLEM_STEP"),
   CURRENT_DIRECT_QUICKPROXYSTATE("MAGMACUBE_WALK", "ENTITY_MAGMACUBE_SQUISH"),
   CURRENT_LINKED_QUICKPROXYSTATE("MAGMACUBE_WALK2", "ENTITY_MAGMACUBE_SQUISH"),
   CURRENT_ROOT_QUICKPROXYSTATE("MAGMACUBE_JUMP", "ENTITY_MAGMACUBE_JUMP"),
   CURRENT_TOP_QUICKPROXYSTATE("PIG_IDLE", "ENTITY_PIG_AMBIENT"),
   CURRENT_FAST_QUICKPROXYSTATE("PIG_DEATH", "ENTITY_PIG_DEATH"),
   CURRENT_SAFE_QUICKPROXYSTATE("PIG_WALK", "ENTITY_PIG_STEP"),
   CURRENT_SECURE_QUICKPROXYSTATE("SHEEP_IDLE", "ENTITY_SHEEP_AMBIENT"),
   CURRENT_OPEN_QUICKPROXYSTATE("SHEEP_SHEAR", "ENTITY_SHEEP_SHEAR"),
   CURRENT_READY_QUICKPROXYSTATE("SHEEP_WALK", "ENTITY_SHEEP_STEP"),
   CURRENT_LIVE_QUICKPROXYSTATE("SILVERFISH_HIT", "ENTITY_SILVERFISH_HURT"),
   PRIMARY_ACTIVE_QUICKPROXYSTATE("SILVERFISH_KILL", "ENTITY_SILVERFISH_DEATH"),
   PRIMARY_PENDING_QUICKPROXYSTATE("SILVERFISH_IDLE", "ENTITY_SILVERFISH_AMBIENT"),
   PRIMARY_CURRENT_QUICKPROXYSTATE("SILVERFISH_WALK", "ENTITY_SILVERFISH_STEP"),
   PRIMARY_MAIN_QUICKPROXYSTATE("SKELETON_IDLE", "ENTITY_SKELETON_AMBIENT"),
   PRIMARY_LOCAL_QUICKPROXYSTATE("SKELETON_DEATH", "ENTITY_SKELETON_DEATH"),
   PRIMARY_REMOTE_QUICKPROXYSTATE("SKELETON_HURT", "ENTITY_SKELETON_HURT"),
   PRIMARY_CACHED_QUICKPROXYSTATE("SKELETON_WALK", "ENTITY_SKELETON_STEP"),
   PRIMARY_STORED_QUICKPROXYSTATE("SLIME_ATTACK", "ENTITY_SLIME_ATTACK"),
   PRIMARY_VERIFIED_QUICKPROXYSTATE("SLIME_WALK", "ENTITY_SLIME_JUMP"),
   PRIMARY_AUTHENTICATED_QUICKPROXYSTATE("SLIME_WALK2", "ENTITY_SLIME_SQUISH"),
   PRIMARY_SHARED_QUICKPROXYSTATE("SPIDER_IDLE", "ENTITY_SPIDER_AMBIENT"),
   PRIMARY_PRIVATE_QUICKPROXYSTATE("SPIDER_DEATH", "ENTITY_SPIDER_DEATH"),
   PRIMARY_INTERNAL_QUICKPROXYSTATE("SPIDER_WALK", "ENTITY_SPIDER_STEP"),
   PRIMARY_UPSTREAM_QUICKPROXYSTATE("WITHER_DEATH", "ENTITY_WITHER_DEATH"),
   PRIMARY_INCOMING_QUICKPROXYSTATE("WITHER_HURT", "ENTITY_WITHER_HURT"),
   PRIMARY_OUTGOING_QUICKPROXYSTATE("WITHER_IDLE", "ENTITY_WITHER_AMBIENT"),
   PRIMARY_SECONDARY_QUICKPROXYSTATE("WITHER_SHOOT", "ENTITY_WITHER_SHOOT"),
   PRIMARY_DIRECT_QUICKPROXYSTATE("WITHER_SPAWN", "ENTITY_WITHER_SPAWN"),
   PRIMARY_LINKED_QUICKPROXYSTATE("WOLF_BARK", "ENTITY_WOLF_AMBIENT"),
   PRIMARY_ROOT_QUICKPROXYSTATE("WOLF_DEATH", "ENTITY_WOLF_DEATH"),
   PRIMARY_TOP_QUICKPROXYSTATE("WOLF_GROWL", "ENTITY_WOLF_GROWL"),
   PRIMARY_FAST_QUICKPROXYSTATE("WOLF_HOWL", "ENTITY_WOLF_HOWL"),
   PRIMARY_SAFE_QUICKPROXYSTATE("WOLF_HURT", "ENTITY_WOLF_HURT"),
   PRIMARY_SECURE_QUICKPROXYSTATE("WOLF_PANT", "ENTITY_WOLF_PANT"),
   PRIMARY_OPEN_QUICKPROXYSTATE("WOLF_SHAKE", "ENTITY_WOLF_SHAKE"),
   PRIMARY_READY_QUICKPROXYSTATE("WOLF_WALK", "ENTITY_WOLF_STEP"),
   PRIMARY_LIVE_QUICKPROXYSTATE("WOLF_WHINE", "ENTITY_WOLF_WHINE"),
   MAIN_ACTIVE_QUICKPROXYSTATE("ZOMBIE_METAL", "ENTITY_ZOMBIE_ATTACK_IRON_DOOR"),
   MAIN_PENDING_QUICKPROXYSTATE("ZOMBIE_WOOD", "ENTITY_ZOMBIE_ATTACK_DOOR_WOOD"),
   MAIN_CURRENT_QUICKPROXYSTATE("ZOMBIE_WOODBREAK", "ENTITY_ZOMBIE_BREAK_DOOR_WOOD"),
   MAIN_PRIMARY_QUICKPROXYSTATE("ZOMBIE_IDLE", "ENTITY_ZOMBIE_AMBIENT"),
   MAIN_LOCAL_QUICKPROXYSTATE("ZOMBIE_DEATH", "ENTITY_ZOMBIE_DEATH"),
   MAIN_REMOTE_QUICKPROXYSTATE("ZOMBIE_HURT", "ENTITY_ZOMBIE_HURT"),
   MAIN_CACHED_QUICKPROXYSTATE("ZOMBIE_INFECT", "ENTITY_ZOMBIE_INFECT"),
   MAIN_STORED_QUICKPROXYSTATE("ZOMBIE_UNFECT", "ENTITY_ZOMBIE_VILLAGER_CONVERTED"),
   MAIN_VERIFIED_QUICKPROXYSTATE("ZOMBIE_REMEDY", "ENTITY_ZOMBIE_VILLAGER_CURE"),
   MAIN_AUTHENTICATED_QUICKPROXYSTATE("ZOMBIE_WALK", "ENTITY_ZOMBIE_STEP"),
   MAIN_SHARED_QUICKPROXYSTATE("ZOMBIE_PIG_IDLE", "ENTITY_ZOMBIE_PIG_AMBIENT"),
   MAIN_PRIVATE_QUICKPROXYSTATE("ZOMBIE_PIG_ANGRY", "ENTITY_ZOMBIE_PIG_ANGRY"),
   MAIN_INTERNAL_QUICKPROXYSTATE("ZOMBIE_PIG_DEATH", "ENTITY_ZOMBIE_PIG_DEATH"),
   MAIN_UPSTREAM_QUICKPROXYSTATE("ZOMBIE_PIG_HURT", "ENTITY_ZOMBIE_PIG_HURT"),
   MAIN_INCOMING_QUICKPROXYSTATE("DIG_WOOL", "BLOCK_CLOTH_BREAK"),
   MAIN_OUTGOING_QUICKPROXYSTATE("DIG_GRASS", "BLOCK_GRASS_BREAK"),
   MAIN_SECONDARY_QUICKPROXYSTATE("DIG_GRAVEL", "BLOCK_GRAVEL_BREAK"),
   MAIN_DIRECT_QUICKPROXYSTATE("DIG_SAND", "BLOCK_SAND_BREAK"),
   MAIN_LINKED_QUICKPROXYSTATE("DIG_SNOW", "BLOCK_SNOW_BREAK"),
   MAIN_ROOT_QUICKPROXYSTATE("DIG_STONE", "BLOCK_STONE_BREAK"),
   MAIN_TOP_QUICKPROXYSTATE("DIG_WOOD", "BLOCK_WOOD_BREAK"),
   MAIN_FAST_QUICKPROXYSTATE("FIREWORK_BLAST", "ENTITY_FIREWORK_BLAST", "ENTITY_FIREWORK_ROCKET_BLAST"),
   MAIN_SAFE_QUICKPROXYSTATE("FIREWORK_BLAST2", "ENTITY_FIREWORK_BLAST_FAR", "ENTITY_FIREWORK_ROCKET_BLAST_FAR"),
   MAIN_SECURE_QUICKPROXYSTATE("FIREWORK_LARGE_BLAST", "ENTITY_FIREWORK_LARGE_BLAST", "ENTITY_FIREWORK_ROCKET_LARGE_BLAST"),
   MAIN_OPEN_QUICKPROXYSTATE("FIREWORK_LARGE_BLAST2", "ENTITY_FIREWORK_LARGE_BLAST_FAR", "ENTITY_FIREWORK_ROCKET_LARGE_BLAST_FAR"),
   MAIN_READY_QUICKPROXYSTATE("FIREWORK_TWINKLE", "ENTITY_FIREWORK_TWINKLE", "ENTITY_FIREWORK_ROCKET_TWINKLE"),
   MAIN_LIVE_QUICKPROXYSTATE("FIREWORK_TWINKLE2", "ENTITY_FIREWORK_TWINKLE_FAR", "ENTITY_FIREWORK_ROCKET_TWINKLE_FAR"),
   LOCAL_ACTIVE_QUICKPROXYSTATE("FIREWORK_LAUNCH", "ENTITY_FIREWORK_LAUNCH", "ENTITY_FIREWORK_ROCKET_LAUNCH"),
   LOCAL_PENDING_QUICKPROXYSTATE("SUCCESSFUL_HIT", "ENTITY_PLAYER_ATTACK_STRONG"),
   LOCAL_CURRENT_QUICKPROXYSTATE("HORSE_ANGRY", "ENTITY_HORSE_ANGRY"),
   LOCAL_PRIMARY_QUICKPROXYSTATE("HORSE_ARMOR", "ENTITY_HORSE_ARMOR"),
   LOCAL_MAIN_QUICKPROXYSTATE("HORSE_BREATHE", "ENTITY_HORSE_BREATHE"),
   LOCAL_REMOTE_QUICKPROXYSTATE("HORSE_DEATH", "ENTITY_HORSE_DEATH"),
   LOCAL_CACHED_QUICKPROXYSTATE("HORSE_GALLOP", "ENTITY_HORSE_GALLOP"),
   LOCAL_STORED_QUICKPROXYSTATE("HORSE_HIT", "ENTITY_HORSE_HURT"),
   LOCAL_VERIFIED_QUICKPROXYSTATE("HORSE_IDLE", "ENTITY_HORSE_AMBIENT"),
   LOCAL_AUTHENTICATED_QUICKPROXYSTATE("HORSE_JUMP", "ENTITY_HORSE_JUMP"),
   LOCAL_SHARED_QUICKPROXYSTATE("HORSE_LAND", "ENTITY_HORSE_LAND"),
   LOCAL_PRIVATE_QUICKPROXYSTATE("HORSE_SADDLE", "ENTITY_HORSE_SADDLE"),
   LOCAL_INTERNAL_QUICKPROXYSTATE("HORSE_SOFT", "ENTITY_HORSE_STEP"),
   LOCAL_UPSTREAM_QUICKPROXYSTATE("HORSE_WOOD", "ENTITY_HORSE_STEP_WOOD"),
   LOCAL_INCOMING_QUICKPROXYSTATE("DONKEY_ANGRY", "ENTITY_DONKEY_ANGRY"),
   LOCAL_OUTGOING_QUICKPROXYSTATE("DONKEY_DEATH", "ENTITY_DONKEY_DEATH"),
   LOCAL_SECONDARY_QUICKPROXYSTATE("DONKEY_HIT", "ENTITY_DONKEY_HURT"),
   LOCAL_DIRECT_QUICKPROXYSTATE("DONKEY_IDLE", "ENTITY_DONKEY_AMBIENT"),
   LOCAL_LINKED_QUICKPROXYSTATE("HORSE_SKELETON_DEATH", "ENTITY_SKELETON_HORSE_DEATH"),
   LOCAL_ROOT_QUICKPROXYSTATE("HORSE_SKELETON_HIT", "ENTITY_SKELETON_HORSE_HURT"),
   LOCAL_TOP_QUICKPROXYSTATE("HORSE_SKELETON_IDLE", "ENTITY_SKELETON_HORSE_AMBIENT"),
   LOCAL_FAST_QUICKPROXYSTATE("HORSE_ZOMBIE_DEATH", "ENTITY_ZOMBIE_HORSE_DEATH"),
   LOCAL_SAFE_QUICKPROXYSTATE("HORSE_ZOMBIE_HIT", "ENTITY_ZOMBIE_HORSE_HURT"),
   LOCAL_SECURE_QUICKPROXYSTATE("HORSE_ZOMBIE_IDLE", "ENTITY_ZOMBIE_HORSE_AMBIENT"),
   LOCAL_OPEN_QUICKPROXYSTATE("VILLAGER_DEATH", "ENTITY_VILLAGER_DEATH"),
   LOCAL_READY_QUICKPROXYSTATE("VILLAGER_HAGGLE", "ENTITY_VILLAGER_TRADING"),
   LOCAL_LIVE_QUICKPROXYSTATE("VILLAGER_HIT", "ENTITY_VILLAGER_HURT"),
   REMOTE_ACTIVE_QUICKPROXYSTATE("VILLAGER_IDLE", "ENTITY_VILLAGER_AMBIENT"),
   REMOTE_PENDING_QUICKPROXYSTATE("VILLAGER_NO", "ENTITY_VILLAGER_NO"),
   REMOTE_CURRENT_QUICKPROXYSTATE("VILLAGER_YES", "ENTITY_VILLAGER_YES");

   private final String name;
   private final String activeName;
   private final String[] names;

   @Nullable
   public static Sound resolveSound(String... instance) {
      if (PacketListener.activeMethod == null) {
         return null;
      }

      Sound target = null;

      for (String data : instance) {
         try {
            target = LoginCheckpoint.loadObject(PacketListener.activeMethod, null, data);
            break;
         } catch (InvocationTargetException | IllegalAccessException request) {
            Throwable result = request.getCause();
            if (!(result instanceof IllegalArgumentException)) {
               throw new RuntimeException("Cannot invoke Sound#valueOf(String) method", request);
            }
         }
      }

      return target;
   }

   @Nullable
   public Sound retrieveSound() {
      Sound target = resolveSound(this.activeName, this.name);
      if (target == null && this.names != null) {
         target = resolveSound(this.names);
      }

      return target;
   }

   public void handleConsumer(Consumer<Sound> target) {
      Sound input = this.retrieveSound();
      if (input != null) {
         target.accept(input);
      }
   }

   QuickProxyState(String output, String context) {
      this.name = output;
      this.activeName = context;
      this.names = null;
   }

   QuickProxyState(String output, String context, String... data) {
      this.name = output;
      this.activeName = context;
      this.names = data;
   }
}
